apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"what":"what"},"name":"nginx","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2020-01-22T22:16:38Z"
  labels:
    app: web_service
    importance: critical
    customer: internal_use
  name: nginx
  namespace: default
  resourceVersion: "221159"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: 8586bc59-f4b3-4e11-a768-be375527f56b
spec:
  containers:
  - image: nginx:1.7.9
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-tbz4n
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-266-node-03
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-tbz4n
    secret:
      defaultMode: 420
      secretName: default-token-tbz4n
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:16:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:19:01Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:19:01Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-22T22:16:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://11978417299416153244ac573ee6eed757f7de10866dece944f7dee1748a7059
    image: docker.io/library/nginx:1.7.9
    imageID: sha256:35d28df486f6150fa3174367499d1eb01f22f5a410afe4b9581ac0e0e58b3eaf
    lastState:
      terminated:
        containerID: containerd://345a1e582632a1d4cb84cfff4d2629b8b1eb042e6c43c21c860175ead23c3412
        exitCode: 0
        finishedAt: "2020-01-22T22:18:43Z"
        reason: Completed
        startedAt: "2020-01-22T22:18:11Z"
    name: nginx
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-01-22T22:19:00Z"
  hostIP: 10.11.235.214
  phase: Running
  podIP: 192.168.83.9
  qosClass: BestEffort
  startTime: "2020-01-22T22:16:49Z"
